# Generated by Django 3.2.7 on 2022-04-16 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_marque', models.IntegerField(blank=True, null=True)),
                ('id_pdv', models.IntegerField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('prenom', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('login', models.CharField(blank=True, max_length=250, null=True)),
                ('mot_passe', models.CharField(blank=True, max_length=250, null=True)),
                ('derniere_activite', models.DateTimeField(blank=True, null=True)),
                ('connecte', models.IntegerField(blank=True, null=True)),
                ('demande_reinitialisation', models.IntegerField(blank=True, null=True)),
                ('date_demande_reinitialisation', models.DateTimeField(blank=True, null=True)),
                ('token_reinitialisation', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('etat', models.IntegerField(blank=True, null=True)),
                ('id_createur', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidBu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('slug', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'fid_bu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidCarteFidelite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=250, unique=True)),
                ('nom', models.CharField(max_length=250)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('type_palier', models.IntegerField(blank=True, null=True)),
                ('coefficient', models.FloatField(blank=True, null=True)),
                ('nbre_point_fidelite_cummule', models.IntegerField(blank=True, null=True)),
                ('recto_carte', models.CharField(blank=True, max_length=250, null=True)),
                ('verso_carte', models.CharField(blank=True, max_length=250, null=True)),
                ('etat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_carte_fidelite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidCarteMagnetique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseigne', models.CharField(blank=True, max_length=45, null=True)),
                ('logo', models.CharField(blank=True, max_length=45, null=True)),
                ('etat', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'fid_carte_magnetique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('etat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.IntegerField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=45, null=True)),
                ('date_naissance', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=250, null=True)),
                ('rib', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidClientMarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_marque', models.PositiveIntegerField()),
                ('nbre_produit_achat', models.IntegerField(blank=True, null=True)),
                ('somme_achat', models.FloatField(blank=True, null=True)),
                ('nbre_point_fid_achat', models.FloatField(blank=True, null=True)),
                ('nbre_point_fid_actuel', models.FloatField(blank=True, null=True)),
                ('nbre_point_fid_global', models.FloatField(blank=True, null=True)),
                ('somme_gagne_actuel', models.FloatField(blank=True, null=True)),
                ('somme_gagne_global', models.FloatField(blank=True, null=True)),
                ('date_achat', models.DateTimeField(blank=True, null=True)),
                ('etat_remboursement', models.IntegerField(blank=True, null=True)),
                ('date_remboursemnt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_client_marque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_mail_contact', models.CharField(blank=True, db_column='adresse_mail _contact', max_length=250, null=True)),
                ('adresse_mail_remarque', models.CharField(blank=True, max_length=250, null=True)),
                ('nbre_points_gagne_partage', models.IntegerField(blank=True, null=True)),
                ('nbre_points_gagne_parrainage', models.IntegerField(blank=True, null=True)),
                ('nbre_points_gagne_checkin', models.IntegerField(blank=True, null=True)),
                ('publicite', models.CharField(blank=True, max_length=250, null=True)),
                ('nbre_points_gagne_publicite', models.IntegerField(blank=True, null=True)),
                ('equivalence_addition_point', models.CharField(blank=True, db_column='equivalence_addition_ point', max_length=250, null=True)),
                ('nbre_additions_etablissemnt', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'fid_configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'fid_delegation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidDroitAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_droit_acces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidGouvernorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'fid_gouvernorat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidKeyWordsMarque',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('key_word', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_key_words_marque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidLocalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'fid_localite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidMarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_google_plus', models.CharField(blank=True, max_length=250, null=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=45, null=True)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('logo_site', models.CharField(blank=True, max_length=250, null=True)),
                ('logo_app', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', models.CharField(blank=True, max_length=250, null=True)),
                ('fax', models.CharField(blank=True, max_length=250, null=True)),
                ('email_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('site_web', models.CharField(blank=True, max_length=250, null=True)),
                ('regime', models.CharField(blank=True, max_length=250, null=True)),
                ('pays_participan_etranger', models.CharField(blank=True, max_length=250, null=True)),
                ('url_fcb', models.CharField(blank=True, max_length=250, null=True)),
                ('url_twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('prenom_responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('titre_responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone_responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('email_responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('etat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_marque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidNbreEmployes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'fid_nbre_employes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidOffre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_pdv', models.IntegerField(blank=True, null=True)),
                ('prospectus', models.CharField(blank=True, max_length=500, null=True)),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('eat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_offre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidPalierPointFid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label_produit_achet', models.CharField(blank=True, max_length=250, null=True)),
                ('nbre_points_fid_equivalente', models.CharField(blank=True, max_length=45, null=True)),
                ('etat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_palier_point_fid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidPalierTampon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_tampon', models.IntegerField(blank=True, null=True)),
                ('equivalence_offre', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'fid_palier_tampon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidPays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('slug', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'fid_pays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidPdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(blank=True, max_length=45, null=True)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('telepphone', models.CharField(blank=True, max_length=45, null=True)),
                ('email_contact', models.CharField(blank=True, max_length=45, null=True)),
                ('site_web', models.CharField(blank=True, max_length=45, null=True)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('nom_responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('prenom_responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('titre_responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone_responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('email_responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('etat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_pdv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidPdvCarteMagnetique',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('longitude', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'fid_pdv_carte_magnetique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidPlaces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('fid_place_name', models.CharField(blank=True, max_length=250, null=True)),
                ('time_consumed', models.DateField()),
                ('fid_marque', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fid_places',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidProduit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('code_barre', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('coefficient_achat_point_fid', models.IntegerField(blank=True, null=True)),
                ('nbre_point_fid', models.IntegerField(blank=True, null=True)),
                ('somme_gagne', models.CharField(blank=True, max_length=45, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('etat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidProspectus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_pdv', models.IntegerField(blank=True, null=True)),
                ('prospectus', models.CharField(blank=True, max_length=500, null=True)),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('eat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_prospectus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidRoleAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q3_role_admin', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'fid_role_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidSecteurActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'fid_secteur_activite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidAdminDroitAcces',
            fields=[
                ('id', models.IntegerField(blank=True, null=True)),
                ('id_admin', models.OneToOneField(db_column='id_admin', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geocalisation.fidadmin')),
            ],
            options={
                'db_table': 'fid_admin_droit_acces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidCarteMagnetiqueClient',
            fields=[
                ('fid_carte_magnetique', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geocalisation.fidcartemagnetique')),
            ],
            options={
                'db_table': 'fid_carte_magnetique_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidClientCarteMagnetique',
            fields=[
                ('id', models.IntegerField(unique=True)),
                ('id_client', models.OneToOneField(db_column='id_client', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geocalisation.fidclient')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fid_client_carte_magnetique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidMarqueHasFidClient',
            fields=[
                ('fid_marque', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geocalisation.fidmarque')),
                ('fid_marque_fid_client_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'fid_marque_has_fid_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FidProduitHasFidClient',
            fields=[
                ('fid_produit', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geocalisation.fidproduit')),
            ],
            options={
                'db_table': 'fid_produit_has_fid_client',
                'managed': False,
            },
        ),
    ]
