# Generated by Django 3.2.7 on 2022-06-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FidAdmin',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_marque', models.BigIntegerField(blank=True, null=True)),
                ('id_pdv', models.BigIntegerField(blank=True, null=True)),
                ('id_carte_magnetique', models.FloatField(blank=True, null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('prenom', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('login', models.TextField(blank=True, null=True)),
                ('mot_passe', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_admin',
                'managed': False,
            },
        ),
    ]
