# Generated by Django 3.2.7 on 2022-06-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FidCarteFidelite',
            fields=[
                ('type_contrat', models.TextField(blank=True, db_collation='utf8_bin', null=True)),
                ('id_admin_creation', models.BigIntegerField(blank=True, null=True)),
                ('code', models.TextField(blank=True, db_collation='utf8_bin', null=True)),
                ('montant_achat_dt_field', models.BigIntegerField(blank=True, db_column='montant_achat (DT)', null=True)),
                ('id_marque', models.BigIntegerField(blank=True, null=True)),
                ('frais_contrat', models.BigIntegerField(blank=True, db_column='Frais_contrat', null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('roi', models.FloatField(blank=True, db_column='ROI', null=True)),
                ('nom', models.TextField(blank=True, db_collation='utf8_bin', null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fid_carte_fidelite',
                'managed': False,
            },
        ),
    ]
